# Files

You need to make sure that:

a) You have access to all of your files 
b) Your files are backed up so your setup is not entirely reliant on a single device
c) Each device on which your files are copied or from which they are accessed
is encrypted

## Backup/sync

The simplest and recommended way to do this at Liverpool is to keep all your
files and data on your university account at OneDrive. This is part of the
Office 365 Suite available from the university, you can find more info at:

> [`https://www.liverpool.ac.uk/csd/working-from-home/`](https://www.liverpool.ac.uk/csd/working-from-home/)

There are Windows and Mac clients that work relatively well (equivalent to
Dropbox client).

Once you are set up, copy all your files onto your OneDrive account, which
will create a copy of them in Microsoft's secure cloud. The exception is
where you have data that has requirements to be managed in particular ways - e.g.
only from a single machine etc; not in the cloud.

Please, be sure to speak with your PhD supervisor if you access data that
may pose some challenges when moving from local machines or within the university
network (remember OneDrive is in the Cloud, not the university servers!).

## Encryption

[Add guide to encryption: what it is and how to set up on
Windows/macOS/Linux/iOS/Android]

## File Transfer

There exists a number of ways through which data can be copied 
loaded onto a remote sever. We shall discuss three such approaches
in detail below, including: 

1) File Transfer Protocol (FTP); 
2) Secure Copy Protocol (scp);
3) wget.

### File Transfer Protocol (FTP)

If you need to move large and/or many files from a local machine to a remote
server (e.g. from your laptop to a Linux machine at the lab), you will
probably want to use something like FTP. 

Can be accessed using any FTP client (e.g., \href{https://filezilla-project.org/}{FileZilla)} using:

Host: Remote Server IP Address (See servers spreadsheet).
Username: Your username on the remote host.
Password: Remote host password.

MobileXTerm can be used to transfer files using FTP:

### Secure Copy Protocol (scp)

> scp ./dataset.zip user@remote_host:~/

### wget

Often data can be downloaded onto a remote server directly via a url. In these cases the wget command can be used to download the data. 

> wget https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz

Once the data has been downloaded we must verify that the integrity of the resource. Typically website from which data can be downloaded provide an md5 checkusum. This allows us to verify that a file has not been changed: 

> md5sum cifar-10-python.tar.gz 
