# VPN

## *What is a VPN?*

A VPN (virtual private network) connects a machine that lies outside of the university (ie. outside the firewall) to the internal network. When the VPN is running, your network traffic (e.g. Internet) is routed through the university in the same way as if the computer was on your work desk. This enables you to:

* Access journal websites like you would inside the university
* Access network drives (e.g. M Drive etc) - but be careful when transferring big files
* Access servers (e.g. over the terminal / command line / ftp)

## *How can I setup the VPN for Liverpool?*

You can find a more comprehensive guide to setup your VPN on the
[`setup_vpn.md`](setup_vpn.md) document of this repository.

## Set up a VPN connection

This document describes how to set up a VPN. The text below has been copied from CSD website.

To access the VPN service:

1. Register

Submit a request to register for the VPN service via CSD. You will need to explain why you require VPN access and what you intend to do with it. It may be that other services offer the solution you require instead of the VPN.

2. Download the VPN Client

Once your registration is confirmed you will need to download and install the GlobalProtect VPN Client if you are using Windows 10.

You will need admin rights in order to download the GlobalProtect VPN Client. This is how to access admin rights on your MWS PC. Please access admin rights before attempting to download the VPN Client. 

The GlobalProtect VPN Client is also compatible with MacOS. Mobile and tablet devices cannot connect using this client. If you are using a Linux distribution, such as Ubuntu, you may be able to connect to the University network using VPNc.

3. Open the client and connect

Click here for instructions on how to use the GlobalProtect VPN Client to access the University network from your PC or Mac. 
