# Data Science Stack

Once you have access from home to all your files and (remote) university computers, next step is easily being able to bootstrap a full data science stack that allows you to carry out scientific work. There are several ways of achieving this, but our preferred strategy is to rely on container technology, in particular on [Docker](https://www.docker.com/). This will allow you to rapidly install the platform and set of libraries you are familiar with in a way that can be easily reproduced and redeployed (e.g. on a remote computer on campus).

Here are a series of pages that will help you get a stack ready to go:

- [Docker]: instructions to install and get Docker
  up and running on different platforms
- [JupyterLab]: instructions to run a JupyterLab server within a Docker container both on local (e.g. laptop) and remote (e.g. server) machines
- [Docker Containers for R]: instructions to run Rstudio server within a Docker container both on local (e.g. laptop) and remote (e.g. server) machines.


